--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BedrockFusion/TheChestLock
build-by-default: true
branches:
- main
projects:
  TheChestLock:
    path: ""
    icon: icon.png
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
...
